### ISSUE TITLE
No actualiza precio al desmarcar checkbox

### ISSUE THREAD

**Issue by Efeyabel** [codigodiario/issues-tracker-conjuntas#3]
Pasos para reproducirlo:
- Clickas el checkbox "Te interesa alguna de las anteriores conjuntas?", pulsas sobre cualquiera
- Te actualiza el precio : 2E -> OK
- Clickas el checkbox "Te interesa alguna de las anteriores conjuntas?", pulsas sobre cualquiera
- Te actualiza el precio : 1E -> OK
- Clickas el checkbox "Te interesa alguna de las anteriores conjuntas?", pulsas sobre cualquiera
- Aparece la anterior conjunta activada, pero el precio que aparece es 1E -> NOT OK
- Clickas el checkbox "Te interesa alguna de las anteriores conjuntas?", pulsas sobre cualquiera

Al pagar te dice que vas a pagar por una conjunta adicional que es falso por que no pusistes que te interesase una conjunta anterior. En paypal pone 1E a pagar

**Comment by codigodiario** [comment]
Fixed
