### ISSUE TITLE
El enlace del mail enviado lleva al portal de forocoches

### ISSUE THREAD

**Issue by Efeyabel** [codigodiario/issues-tracker-conjuntas#4]
Al recibir un e-mail y al pulsar en el link inferior te lleva a la pagina de forocoches el portal. No al hilo de las conjuntas

[https://imgur.com/zG4jlph](img)
![screenshot_8](https://user-images.githubusercontent.com/16035227/45671322-753e4780-bb25-11e8-94f7-a9966affdf59.png)

**Comment by codigodiario** [comment]
Fixed
